const data=[
    {
        key:1,
        img:"public/furniture/img1.webp",
        Title:"Wood Finish Table",
        category:"furniture",
        desc:""
    },
    {
        key:2,
        img:"",
        Title:"",
        category:"plants",
        desc:""
    },
    {
        key:3,
        img:"",
        Title:"",
        category:"soft toys",
        desc:""
    },
    {
        key:4,
        img:"",
        Title:"Table lamp",
        category:"lamps",
        desc:""
    },
    {
        key:5,
        img:"",
        Title:"Wall Shelve",
        category:"furniture",
        desc:""
    },
    {
        key:6,
        img:"",
        Title:"",
        category:"plants",
        desc:""
    },
    {
        key:7,
        img:"",
        Title:"",
        category:"soft toys",
        desc:""
    },
    {
        key:8,
        img:"",
        Title:"reading lamp",
        category:"lamps",
        desc:""
    },
    {
        key:9,
        img:"",
        Title:"Mirror",
        category:"furniture",
        desc:""
    },
    {
        key:10,
        img:"",
        Title:"",
        category:"plants",
        desc:""
    },
    {
        key:11,
        img:"",
        Title:"",
        category:"soft toys",
        desc:""
    },
    {
        key:12,
        img:"",
        Title:"Night Lamp",
        category:"lamps",
        desc:""
    },
    {
        key:13,
        img:"",
        Title:"Wardrobe",
        category:"furniture",
        desc:""
    },
    {
        key:14,
        img:"",
        Title:"",
        category:"plants",
        desc:""
    },
    {
        key:15,
        img:"",
        Title:"",
        category:"soft toys",
        desc:""
    },
    {
        key:16,
        img:"",
        Title:"",
        category:"lamps",
        desc:""
    },
    {
        key:17,
        img:"",
        Title:"",
        category:"furniture",
        desc:""
    },
    {
        key:18,
        img:"",
        Title:"",
        category:"plants",
        desc:""
    },
    {
        key:19,
        img:"",
        Title:"Wall Shelve",
        category:"furniture",
        desc:""
    },
    {
        key:20,
        img:"",
        Title:"Table lamp",
        category:"lamps",
        desc:""
    },
]